class AvaliacaoServiceFixo {

  String retornoAvaliacao = '{'
      '"id": 1, '
      '"idUsuario": 1, '
      '"idAvaliado": 2, '
      '"data": "2020-07-01", '
      '"status": "1", '
      '"respostaPe": "1", '
      '"respostaLevantada": "1", '
      '"respostaRecepcao": "1", '
      '"respostaAtaque": "1", '
      '"respostaDefesa": "1", '
      '"respostaShark": "1", '
      '"respostaFintaPescoco": "1", '
      '"respostaFintaOmbro": "1", '
      '"respostaConstante": "1", '
      '"respostaVariacao": "1", '
      '"respostaInteligente": "1", '
      '"respostaTatico": "1", '
      '"respostaCompetitivo": "1", '
      '"respostaPreparo": "1", '
      '"nomeUsuario": "Robson", '
      '"nomeAvaliado": "LEVANTADA", '
      '"fotoUsuario": "", '
      '"fotoAvaliado": "https://i.pinimg.com/originals/88/31/be/8831be300e5b4b7758f0bc34ef6d5db8.jpg" '
    '}';

  String retornoAvaliacoes = '['
      '{'
        '"id": 1, '
        '"idUsuario": 1, '
        '"idAvaliado": 2, '
        '"data": "2020-07-01", '
        '"status": "1", '
        '"respostaPe": "1", '
        '"respostaLevantada": "1", '
        '"respostaRecepcao": "1", '
        '"respostaAtaque": "1", '
        '"respostaDefesa": "1", '
        '"respostaShark": "1", '
        '"respostaFintaPescoco": "1", '
        '"respostaFintaOmbro": "1", '
        '"respostaConstante": "1", '
        '"respostaVariacao": "1", '
        '"respostaInteligente": "1", '
        '"respostaTatico": "1", '
        '"respostaCompetitivo": "1", '
        '"respostaPreparo": "1", '
        '"nomeUsuario": "Robson", '
        '"nomeAvaliado": "Messi", '
        '"fotoUsuario": "", '
        '"fotoAvaliado": "https://i.pinimg.com/originals/88/31/be/8831be300e5b4b7758f0bc34ef6d5db8.jpg" '
      '}, '
      '{'
        '"id": 1, '
        '"idUsuario": 1, '
        '"idAvaliado": 2, '
        '"data": "2020-07-01", '
        '"status": "1", '
        '"respostaPe": "1", '
        '"respostaLevantada": "1", '
        '"respostaRecepcao": "1", '
        '"respostaAtaque": "1", '
        '"respostaDefesa": "1", '
        '"respostaShark": "1", '
        '"respostaFintaPescoco": "1", '
        '"respostaFintaOmbro": "1", '
        '"respostaConstante": "1", '
        '"respostaVariacao": "1", '
        '"respostaInteligente": "1", '
        '"respostaTatico": "1", '
        '"respostaCompetitivo": "1", '
        '"respostaPreparo": "1", '
        '"nomeUsuario": "Robson", '
        '"nomeAvaliado": "Suarez", '
        '"fotoUsuario": "", '
        '"fotoAvaliado": "https://3.bp.blogspot.com/-HCGJETqqJP0/VDspCWJ_1DI/AAAAAAAAAoI/warI-4pJH9A/s1600/suarez14.jpg" '
      '}, '
      '{'
        '"id": 1, '
        '"idUsuario": 1, '
        '"idAvaliado": 2, '
        '"data": "2020-07-01", '
        '"status": "1", '
        '"respostaPe": "1", '
        '"respostaLevantada": "1", '
        '"respostaRecepcao": "1", '
        '"respostaAtaque": "1", '
        '"respostaDefesa": "1", '
        '"respostaShark": "1", '
        '"respostaFintaPescoco": "1", '
        '"respostaFintaOmbro": "1", '
        '"respostaConstante": "1", '
        '"respostaVariacao": "1", '
        '"respostaInteligente": "1", '
        '"respostaTatico": "1", '
        '"respostaCompetitivo": "1", '
        '"respostaPreparo": "1", '
        '"nomeUsuario": "Robson", '
        '"nomeAvaliado": "MBappé", '
        '"fotoUsuario": "", '
        '"fotoAvaliado": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg" '
      '}'
    ']';

  String responseLista() {
    return retornoAvaliacoes;
  }

  String responseObjeto() {
    return retornoAvaliacao;
  }

}