class JogoRedeServiceFixo {

  String retornoJogo = '{'
        '"id": 1, '
        '"numero": 1, '
        '"pontuacao1": 18, '
        '"pontuacao2": 12, '
        '"data": null, '
        '"idRede": 4, '
        '"idJogador1": 1, '
        '"idJogador2": 2, '
        '"idJogador3": 3, '
        '"idJogador4": 4, '
        '"idJogador5": 0, '
        '"idJogador6": 0, '
        '"idJogador7": 0, '
        '"idJogador8": 0, '
        '"idJogador9": 0, '
        '"idJogador10": 0, '
        '"nomeJogador1": "", '
        '"nomeJogador2": "", '
        '"nomeJogador3": "", '
        '"nomeJogador4": "", '
        '"nomeJogador5": "", '
        '"nomeJogador6": "", '
        '"nomeJogador7": "", '
        '"nomeJogador8": "", '
        '"nomeJogador9": "", '
        '"nomeJogador10": "", '
        '"apelidoJogador1": "", '
        '"apelidoJogador2": "", '
        '"apelidoJogador3": "", '
        '"apelidoJogador4": "", '
        '"apelidoJogador5": "", '
        '"apelidoJogador6": "", '
        '"apelidoJogador7": "", '
        '"apelidoJogador8": "", '
        '"apelidoJogador9": "", '
        '"apelidoJogador10": ""'
      '}';

  String retornoJogosDataX = '[ '
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 0, '
          '"pontuacao2": 0, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 10, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '},'
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 10, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '},'
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 10, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '} '
      ']';

  String retornoJogosDataY = '[ '
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 10, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 10, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '} '
      ']';

  String retornoJogosDataY_atualizado = '[ '
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 18, '
          '"pontuacao2": 12, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 7, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 1, '
          '"numero": 1, '
          '"pontuacao1": 7, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 1, '
          '"idJogador2": 2, '
          '"idJogador3": 3, '
          '"idJogador4": 4, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '}, '
        '{'
          '"id": 2, '
          '"numero": 2, '
          '"pontuacao1": 10, '
          '"pontuacao2": 18, '
          '"data": null, '
          '"idRede": 4, '
          '"idJogador1": 5, '
          '"idJogador2": 6, '
          '"idJogador3": 7, '
          '"idJogador4": 8, '
          '"idJogador5": 0, '
          '"idJogador6": 0, '
          '"idJogador7": 0, '
          '"idJogador8": 0, '
          '"idJogador9": 0, '
          '"idJogador10": 0, '
          '"nomeJogador1": "Robson", '
          '"nomeJogador2": "Pedro", '
          '"nomeJogador3": "Iuca", '
          '"nomeJogador4": "Lucas", '
          '"nomeJogador5": "", '
          '"nomeJogador6": "", '
          '"nomeJogador7": "", '
          '"nomeJogador8": "", '
          '"nomeJogador9": "", '
          '"nomeJogador10": "", '
          '"apelidoJogador1": "Robinho", '
          '"apelidoJogador2": "Pedrinho", '
          '"apelidoJogador3": "Iuquiba", '
          '"apelidoJogador4": "Luquinhas", '
          '"apelidoJogador5": "", '
          '"apelidoJogador6": "", '
          '"apelidoJogador7": "", '
          '"apelidoJogador8": "", '
          '"apelidoJogador9": "", '
          '"apelidoJogador10": ""'
        '} '
      ']';

  String responseLista(int dia) {
    if (dia == 1) {
      return retornoJogosDataX;
    }else if (dia == 2) {
      return retornoJogosDataY;
    }
  }

  String responseListaPlacarAtualizado(int dia) {
    if (dia == 1) {
      return retornoJogosDataX;
    }else if (dia == 2) {
      return retornoJogosDataY_atualizado;
    }
  }

  String responseObjeto() {
    return retornoJogo;
  }
}