class ResultadoServiceFixo {

  String retornoResultados = '['
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 1,'
          '"idJogador2": 2,'
          '"nomeJogador1": "Messi",'
          '"nomeJogador2": "Suarez",'
          '"apelidoJogador1": "Robinho",'
          '"apelidoJogador2": "Pedrinho",'
          '"fotoJogador1": "https://i.pinimg.com/originals/88/31/be/8831be300e5b4b7758f0bc34ef6d5db8.jpg",'
          '"fotoJogador2": "https://3.bp.blogspot.com/-HCGJETqqJP0/VDspCWJ_1DI/AAAAAAAAAoI/warI-4pJH9A/s1600/suarez14.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 3,'
          '"idJogador2": 4,'
          '"nomeJogador1": "Neymar",'
          '"nomeJogador2": "MBappe",'
          '"apelidoJogador1": "Luquibas",'
          '"apelidoJogador2": "Iuquiba",'
          '"fotoJogador1": "https://live.staticflickr.com/6149/5961504337_219dd6d45a_n.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 1,'
          '"idJogador2": 2,'
          '"nomeJogador1": "Ronaldinho Gaúcho",'
          '"nomeJogador2": "Rivaldo",'
          '"apelidoJogador1": "Gurgel",'
          '"apelidoJogador2": "Pessoa",'
          '"fotoJogador1": "https://cdna.artstation.com/p/assets/images/images/011/583/200/large/marcelo-lima-26187682-1971683559710857-21601598144774144-n.jpg?1530311997",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 3,'
          '"idJogador2": 4,'
          '"nomeJogador1": "Davi",'
          '"nomeJogador2": "Batan",'
          '"apelidoJogador1": "Davi",'
          '"apelidoJogador2": "Iuba",'
          '"fotoJogador1": "https://i.pinimg.com/originals/1a/64/50/1a64503c82c12a2f1aea73cbad418db7.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 1,'
          '"idJogador2": 2,'
          '"nomeJogador1": "Robson",'
          '"nomeJogador2": "Pedro",'
          '"apelidoJogador1": "Robinho",'
          '"apelidoJogador2": "Pedrinho",'
          '"fotoJogador1": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 3,'
          '"idJogador2": 4,'
          '"nomeJogador1": "Lucas",'
          '"nomeJogador2": "Iuca",'
          '"apelidoJogador1": "Luquibas",'
          '"apelidoJogador2": "Iuquiba",'
          '"fotoJogador1": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 1,'
          '"idJogador2": 2,'
          '"nomeJogador1": "Fabio",'
          '"nomeJogador2": "João",'
          '"apelidoJogador1": "Gurgel",'
          '"apelidoJogador2": "Pessoa",'
          '"fotoJogador1": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 3,'
          '"idJogador2": 4,'
          '"nomeJogador1": "Davi",'
          '"nomeJogador2": "Batan",'
          '"apelidoJogador1": "Davi",'
          '"apelidoJogador2": "Iuba",'
          '"fotoJogador1": "https://i.pinimg.com/originals/50/65/c9/5065c907335f6cf04a5d1db7408036c9.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 1,'
          '"idJogador2": 2,'
          '"nomeJogador1": "Robson",'
          '"nomeJogador2": "Pedro",'
          '"apelidoJogador1": "Robinho",'
          '"apelidoJogador2": "Pedrinho",'
          '"fotoJogador1": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 3,'
          '"idJogador2": 4,'
          '"nomeJogador1": "Lucas",'
          '"nomeJogador2": "Iuca",'
          '"apelidoJogador1": "Luquibas",'
          '"apelidoJogador2": "Iuquiba",'
          '"fotoJogador1": "https://live.staticflickr.com/5116/5862708162_d0bc38a073_z.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 1,'
          '"idJogador2": 2,'
          '"nomeJogador1": "Fabio",'
          '"nomeJogador2": "João",'
          '"apelidoJogador1": "Gurgel",'
          '"apelidoJogador2": "Pessoa",'
          '"fotoJogador1": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '},'
        '{'
          '"idTorneio": 9,'
          '"tituloTorneio": "Copa Brasil de Futevolei",'
          '"dataTorneio": "10.08.2020",'
          '"paisTorneio": "Brasil",'
          '"cidadeTorneio": "Rio de Janeiro",'
          '"idJogador1": 3,'
          '"idJogador2": 4,'
          '"nomeJogador1": "Davi",'
          '"nomeJogador2": "Batan",'
          '"apelidoJogador1": "Davi",'
          '"apelidoJogador2": "Iuba",'
          '"fotoJogador1": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg",'
          '"fotoJogador2": "https://pbs.twimg.com/media/Dk0iKh4XoAERLOB.jpg"'
        '}'
      ']';

  String responseLista() {
    return retornoResultados;
  }

}