import 'dart:convert';
import 'package:futt/futt/model/TorneioModel.dart';

class TorneioServiceFixo {

  String retornoTorneio = '{ '
        '"id": 4, '
        '"nome": "TAFC 1", '
        '"status": 10, '
        '"pais": "Brasil", '
        '"estado": null, '
        '"cidade": "Rio de Janeiro", '
        '"local": "Leblon", '
        '"dataInicio": "2020-07-01", '
        '"dataFim": "2020-07-03", '
        '"ano": 0, '
        '"qtdDuplas": 8, '
        '"genero": "1", '
        '"info": null, '
        '"usuarioAdministrador": 1, '
        '"atletaCampeao1": 0, '
        '"atletaCampeao2": 0, '
        '"atletaCampeao3": 0, '
        '"atletaCampeao4": 0, '
        '"atletaCampeao5": 0, '
        '"atletaViceCampeao1": 0, '
        '"atletaViceCampeao2": 0, '
        '"atletaViceCampeao3": 0, '
        '"atletaViceCampeao4": 0, '
        '"atletaViceCampeao5": 0, '
        '"atletaTerceiroLugar1": 0, '
        '"atletaTerceiroLugar2": 0, '
        '"atletaTerceiroLugar3": 0, '
        '"atletaTerceiroLugar4": 0, '
        '"atletaTerceiroLugar5": 0, '
        '"tipo": { '
          '"id": 2, '
          '"nome": "Eliminatória simples", '
          '"descricao": null,  '
          '"geracaoJogos": "S" '
        '}, '
        '"entidade": null, '
        '"classificacao": { '
          '"id": 1, '
          '"nome": '
          '"Profissional", '
          '"descricao": "" '
        '}, '
        '"rankingEntidade": null, '
        '"idTipoTorneio": 0, '
        '"idEntidade": 0, '
        '"idClassificacao": 0, '
        '"idRankingEntidade": 0 '
      '} ';

  String retornoTorneios = '[ '
        '{ '
          '"id": 4, '
          '"nome": "TAFC 1", '
          '"status": 10, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://baladasegura.rs.gov.br/themes/modelo-institucional/images/outros/GD_imgSemImagem.png" '
        '},'
        '{ '
          '"id": 5, '
          '"nome": "TAFC 2", '
          '"status": 20, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://static.wixstatic.com/media/7b7a56_6505d03965af43ef849dd2e3dbe7ee21~mv2.jpg/v1/fill/w_800,h_800,al_c,q_90/7b7a56_6505d03965af43ef849dd2e3dbe7ee21~mv2.jpg" '
        '},'
        '{ '
          '"id": 5, '
          '"nome": "Copa Lafutma", '
          '"status": 30, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://4.bp.blogspot.com/-AMt7MsJf5HQ/WSL0nF4NS8I/AAAAAAABIjI/lYyqPt9zwv49ZKbJ6HtcfInDRNZuwa4lACEw/s1600/13164429_120676181678503_3422578174887740271_n.jpg" '
        '},'
        '{ '
          '"id": 7, '
          '"nome": "Campeonato Português de Futevolley", '
          '"status": 40, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://baladasegura.rs.gov.br/themes/modelo-institucional/images/outros/GD_imgSemImagem.png" '
        '},'
        '{ '
          '"id": 8, '
          '"nome": "Copa Fut Portugal", '
          '"status": 50, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://futevolei.pt/assets/img/news/60-iii-meeting-futevolei-portugal-brought-together-national-representatives.jpg" '
        '},'
        '{ '
          '"id": 8, '
          '"nome": "Campeonato Brasileiro de Futevolley", '
          '"status": 60, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://s1.static.brasilescola.uol.com.br/be/e/cbfv.jpg" '
        '},'
        '{ '
          '"id": 8, '
          '"nome": "Liga do Pontal", '
          '"status": 70, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://1.bp.blogspot.com/-pE3ICzSh_ao/WHZEZGxcCWI/AAAAAAAAcwU/VE76VSJmWk4upz5C67-BvOPL-r3Lut4_QCK4B/s1600/IMG-20170111-WA0010-763148.jpg" '
        '} '
      ']';

  String retornoTorneiosFiltro = '[ '
        '{ '
          '"id": 4, '
          '"nome": "TAFC 1", '
          '"status": 1, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
          '"id": 2, '
          '"nome": "Eliminatória simples", '
          '"descricao": null,  '
          '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
          '"id": 1, '
          '"nome": '
          '"Profissional", '
          '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://baladasegura.rs.gov.br/themes/modelo-institucional/images/outros/GD_imgSemImagem.png" '
        '},'
        '{ '
          '"id": 5, '
          '"nome": "TAFC 2", '
          '"status": 1, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
          '"id": 2, '
          '"nome": "Eliminatória simples", '
          '"descricao": null,  '
          '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
          '"id": 1, '
          '"nome": '
          '"Profissional", '
          '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://static.wixstatic.com/media/7b7a56_6505d03965af43ef849dd2e3dbe7ee21~mv2.jpg/v1/fill/w_800,h_800,al_c,q_90/7b7a56_6505d03965af43ef849dd2e3dbe7ee21~mv2.jpg" '
        '},'
        '{ '
          '"id": 5, '
          '"nome": "Copa Lafutma", '
          '"status": 4, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
          '"id": 2, '
          '"nome": "Eliminatória simples", '
          '"descricao": null,  '
          '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
          '"id": 1, '
          '"nome": '
          '"Profissional", '
          '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://4.bp.blogspot.com/-AMt7MsJf5HQ/WSL0nF4NS8I/AAAAAAABIjI/lYyqPt9zwv49ZKbJ6HtcfInDRNZuwa4lACEw/s1600/13164429_120676181678503_3422578174887740271_n.jpg" '
        '}'
      ']';

  String retornoMeusTorneios = '[ '
        '{ '
          '"id": 8, '
          '"nome": "Copa Fut Portugal", '
          '"status": 30, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": { '
            '"id": 2, '
            '"nome": "TAF_PROFISSIONAL", '
            '"descricao": "TAF - Profissional" '
          '}, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://futevolei.pt/assets/img/news/60-iii-meeting-futevolei-portugal-brought-together-national-representatives.jpg" '
        '},'
        '{ '
          '"id": 9, '
          '"nome": "Campeonato Brasileiro de Futevolley", '
          '"status": 40, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://baladasegura.rs.gov.br/themes/modelo-institucional/images/outros/GD_imgSemImagem.png" '
        '},'
        '{ '
          '"id": 10, '
          '"nome": "Liga do Pontal", '
          '"status": 50, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "1", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://1.bp.blogspot.com/-pE3ICzSh_ao/WHZEZGxcCWI/AAAAAAAAcwU/VE76VSJmWk4upz5C67-BvOPL-r3Lut4_QCK4B/s1600/IMG-20170111-WA0010-763148.jpg" '
        '}, '
        '{ '
          '"id": 11, '
          '"nome": "Liga do Pontal", '
          '"status": 70, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "2", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
          '"id": 2, '
          '"nome": "Eliminatória simples", '
          '"descricao": null,  '
          '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
          '"id": 1, '
          '"nome": '
          '"Profissional", '
          '"descricao": "" '
        '}, '
        '"rankingEntidade": null, '
        '"idTipoTorneio": 0, '
        '"idEntidade": 0, '
        '"idClassificacao": 0, '
        '"idRankingEntidade": 1, '
        '"logoTorneio": "https://1.bp.blogspot.com/-pE3ICzSh_ao/WHZEZGxcCWI/AAAAAAAAcwU/VE76VSJmWk4upz5C67-BvOPL-r3Lut4_QCK4B/s1600/IMG-20170111-WA0010-763148.jpg" '
        '}, '
        '{ '
          '"id": 12, '
          '"nome": "Liga do Pontal", '
          '"status": 60, '
          '"pais": "Brasil", '
          '"estado": null, '
          '"cidade": "Rio de Janeiro", '
          '"local": "Leblon", '
          '"dataInicio": "2020-07-01", '
          '"dataFim": "2020-07-03", '
          '"ano": 0, '
          '"qtdDuplas": 8, '
          '"genero": "3", '
          '"info": null, '
          '"usuarioAdministrador": 1, '
          '"atletaCampeao1": 0, '
          '"atletaCampeao2": 0, '
          '"atletaCampeao3": 0, '
          '"atletaCampeao4": 0, '
          '"atletaCampeao5": 0, '
          '"atletaViceCampeao1": 0, '
          '"atletaViceCampeao2": 0, '
          '"atletaViceCampeao3": 0, '
          '"atletaViceCampeao4": 0, '
          '"atletaViceCampeao5": 0, '
          '"atletaTerceiroLugar1": 0, '
          '"atletaTerceiroLugar2": 0, '
          '"atletaTerceiroLugar3": 0, '
          '"atletaTerceiroLugar4": 0, '
          '"atletaTerceiroLugar5": 0, '
          '"tipo": { '
            '"id": 2, '
            '"nome": "Eliminatória simples", '
            '"descricao": null,  '
            '"geracaoJogos": "S" '
          '}, '
          '"entidade": null, '
          '"classificacao": { '
            '"id": 1, '
            '"nome": '
            '"Profissional", '
            '"descricao": "" '
          '}, '
          '"rankingEntidade": null, '
          '"idTipoTorneio": 0, '
          '"idEntidade": 0, '
          '"idClassificacao": 0, '
          '"idRankingEntidade": 0, '
          '"logoTorneio": "https://baladasegura.rs.gov.br/themes/modelo-institucional/images/outros/GD_imgSemImagem.png" '
        '} '
      ']';

  String responseLista() {
    return retornoTorneios;
  }

  String responseFiltro() {
    return retornoTorneiosFiltro;
  }

  String responseMeusTorneios() {
    return retornoMeusTorneios;
  }

  String responseObjeto() {
    return retornoTorneio;
  }

  Future<List<TorneioModel>> _listaTorneiosFixo() async {
    var dadosJson = json.decode(retornoTorneios);
    List<TorneioModel> lista = List();
    for (var registro in dadosJson) {
      TorneioModel torneioModel = TorneioModel.fromJson(registro); //.converteJson
      lista.add(torneioModel);
    }
    return lista;
  }

  Future<List<TorneioModel>> listaPorFiltros(var torneioModel) async {
    return _listaTorneiosFixo();
  }

  Future<List<TorneioModel>> listaPorStatus(var status) async {
    return _listaTorneiosFixo();
  }

  Future<List<TorneioModel>> listaTodos() async {
    return _listaTorneiosFixo();
  }

}